### ISSUE TITLE
This tool only supports OVF files created by oVirt engine.

### ISSUE THREAD

**Issue by hacxman** [oVirt/ovirt-image-uploader#1]
As a user I would expect this tool to accept standardized OVF format.

**Comment by sandrobonazzola** [comment]
Thanks for the report. You may use virt-v2v for converting any other ovf format to ovirt/rhev format.

**Comment by david-caro** [comment]
Hi, this issue tracker is not active, please open a bug at http://bugzilla.redhat.com if this is still an issue, thanks
